# Generated by Django 2.1.7 on 2019-03-17 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='articles',
            field=models.ManyToManyField(blank=True, to='blog.Article'),
        ),
        migrations.AlterField(
            model_name='writer',
            name='age',
            field=models.PositiveIntegerField(),
        ),
    ]
