# Generated by Django 2.1.7 on 2019-03-17 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190317_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writer',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
